main = ".open-next/worker.js"
name = "publicala-website"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "publica.la"
custom_domain = true

[[routes]]
pattern = "www.publica.la"
custom_domain = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"