export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function PricingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      {children}
    </>
  )
}
